### ISSUE TITLE
negation

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [vonDonnerstein/StringParserPEG.jl#2]
I'm new to PEG but looked at https://pest.rs/ before coming here. I'm surprised not to find negation in the rule set (`!` in pest). How do you achieve the [negative predicate](https://pest.rs/book/grammars/syntax.html#predicates)?

**Comment by vonDonnerstein** [comment]
Thanks for raising this @Hugo-Trentesaux. I've just added negation and added an explanation to README.md (checkout master to get the latest commit). Let me know if anything isn't working as expected for you

**Comment by Hugo-Trentesaux** [comment]
I am curious: how could you perform the example given in your "On the subject of negation" section before introducing negation?

**Comment by vonDonnerstein** [comment]
One way is
```
g = Grammar("""start => '<<' & end
               end   => '>>' | r(.)r & end""")
```
