### ISSUE TITLE
isn't node.children always an array?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [vonDonnerstein/StringParserPEG.jl#5]
You check [twice](https://github.com/vonDonnerstein/StringParserPEG.jl/search?q=if+isa%28node.children%2C+Array%29&unscoped_q=if+isa%28node.children%2C+Array%29) if `node.children` is an `Array`:
```julia
if isa(node.children, Array)
```
but according to the definition of Node, children is an Array:
```julia
struct Node
    name::AbstractString
    value::AbstractString
    first::Int
    last::Int
    children::Array #::Array{Node}
    ruleType::Type
end
```
so what's the point of testing it?

**Comment by vonDonnerstein** [comment]
That's a good point. I previously wanted to support subtree-conversion, but never fully implemented it. I think until someone has a particular use-case for it (which I can't see right now), we'll just stick with the current design, so I've now elimated those confusing if-statements. Thanks

**Comment by Hugo-Trentesaux** [comment]
Nice, you're quick to address things even when they're not really an issue!
What do you mean by subtree-conversion? (and by the way, if you prefer me to ask questions somewhere else than GitHub, where should I?)

**Comment by vonDonnerstein** [comment]
You're welcome :) By subtree-conversion I mean converting parts of the AST into a different datastructure. I can come up with theoretical use-cases (like singletons and performance optimization), but as long as I don't need any of those myself and nobody asks for them, I won't support that for now. 

And yes, I think github is the best place to raise code related questions - but thanks for offering :)
